### ISSUE TITLE
ModuleNotFoundError: No module named 'mem_transformer'

### ISSUE THREAD

**Issue by aletote** [chrisdonahue/LakhNES#1]
Traceback (most recent call last):
  File "generate.py", line 49, in <module>
    model = torch.load(f)
  File "/Users/ale/Desktop/LakhNES/LakhNES-model/lib/python3.7/site-packages/torch/serialization.py", line 368, in load
    return _load(f, map_location, pickle_module)
  File "/Users/ale/Desktop/LakhNES/LakhNES-model/lib/python3.7/site-packages/torch/serialization.py", line 542, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'mem_transformer'

**Comment by chrisdonahue** [comment]
Sorry, I just saw this. The "mem_transformer" module is loaded dynamically by the script because of licensing issues (I wanted to keep the module code which is differently-licensed in a separate directory from the code I wrote).

The issues is somewhere with these lines and how they are working on your local system:

```
  script_dir = os.path.dirname(os.path.abspath(__file__))
  code_model_dir = os.path.abspath(os.path.join(script_dir, 'model'))
  code_utils_dir = os.path.join(code_model_dir, 'utils')
  sys.path.extend([code_model_dir, code_utils_dir])
```

Did you clone the entire repository or just the `generate` script? You might have also run the generate script from somewhere other than the repository root directory.

Let me know if this solves the problem
